### ISSUE TITLE
As a user, I want to user  enter quiz mode, so that I can test my knowledge on a collection of flashcards

### ISSUE THREAD

**Issue by lungsin** [CS2103-AY1819S2-T12-2/main#28]
Some things to do:
- [x] Implement command to enter quiz mode. 
- [ ] Implement command to quit quiz mode.
- [ ] Implement command to give feedback on quiz mode.
- [x] Design the UI in the quiz mode. #26 
- [ ] Implement recommendation system based on statistics.
