### ISSUE TITLE
As a user, I want to be able to insert images

### ISSUE THREAD

**Issue by robincyu** [CS2103-AY1819S2-T12-2/main#32]
Inserting images is an integral part of flashcard apps. It can help strengthen the memory of language learners by directly associating foreign words with concepts rather than using English as an intermediary.

Currently, images are not supported. I want to be able to add images.

Some things to do:
- [x] Display images on the flashcard view.
- [x] Modify add and edit commands to allow insertion of references to images already in the filesystem.
- [x] Remove images by specifying an empty image tag in the edit command.
- [x] Create a command to import images into _Acquizition_.
- [x] Add tests for the above methods.
